language: python

# Worry about Python 3.8 later
python:
    - "3.6"

# TODO : flake8/linting, 
before_install:
    - pip install -U mypy

install:
    - pip install --upgrade pip && pip install -r requirements.txt
    - pip install .

script:
    - mypy parsercom/
    - pytest -vv
